### ISSUE TITLE
Unable to load color "color-235" [2 times]

### ISSUE THREAD

**Issue by dotmilk** [greduan/emacs-theme-gruvbox#37] opened 2016-08-08 05:53 UTC
```
Unable to load color "color-229"
Unable to load color "color-235" [2 times]
Unable to load color "color-229"
Unable to load color "color-235"
Unable to load color "color-229"
Unable to load color "color-235"
Unable to load color "color-229"
Unable to load color "color-235"
Unable to load color "color-229" [3 times]
Unable to load color "color-235"
Unable to load color "color-229"
Unable to load color "color-235"
Unable to load color "color-239"
Unable to load color "color-235" [4 times]
```

Theme appears to be ok, but I am unsure. Only does this in terminal, in cocoa everything is totally fine.

Noticed someone else [here](http://emacs.stackexchange.com/questions/965/unable-to-load-color-color-235-when-using-gruvbox-theme), who had the same problem.

Let me know if I can provide you with more details.

**Comment by greduan** [comment] 2016-08-08 07:33
While it's true what that SO answer says, which is that we should let Emacs do the converting of the full colour to 256 colours, the reason we don't is simply so that we use the exact same colours as the Gruvbox original theme (because that's how it's done in Vim).

What do you think @jasonm23, should we just let Emacs do the color conversion, considering it's an Emacs theme?

**Comment by jasonm23** [comment] 2016-08-08 07:43
@greduan nearest match translation isn't performed and so the resulting values can be unpleasant.

The correct way to do this is to use the theme color class system, which is a little unpleasant to use, but we will avoid the drawbacks of `display-graphic-p`

I definitely do not recommend letting Emacs convert terminal colors on its own, because it sucks at it.

**Comment by jasonm23** [comment] 2016-08-08 07:44
@cheshirecatalyst - please ensure your terminal is `xterm-256color`

**Comment by cheshirecatalyst** [comment] 2016-08-08 09:05
@jasonm23 - that is what the terminal reports and what iterm2 is set to etc and so on

**Comment by jasonm23** [comment] 2016-09-12 04:02
Hi @dotmilk 

I've looked into this and when the Emacs message is being sent, the color still loads as expected.

I think we can close this.

**Comment by jasonm23** [comment] 2016-09-12 04:11
I think this is maybe mac specific, see this post.

http://apple.stackexchange.com/questions/84685/how-can-i-fix-a-missing-color-in-emacs

**Comment by mekeor** [comment] 2016-09-22 08:26
I have this issue, too. Both on Mac OS as well as  Debian GNU/Linux. So it's not Mac specific.

**Comment by jasonm23** [comment] 2016-09-22 09:47
Confirmed, it's Emacs, not OS specific, but the colors set correctly anyway, as long as the terminal is configured as xterm 256 or compatible.

I think this issue can be closed.

**Comment by dotmilk** [comment] 2016-09-22 17:09
To clarify, my problem isn't that it didn't display correctly, just that it is too noisy during startup. I have subsequently changed themes.

**Comment by mekeor** [comment] 2016-09-23 09:47
The issue occurs for me because my emacs daemon is launched automatically on boot. [This answer](http://emacs.stackexchange.com/a/26138/13390) on Emacs-StackExchange explains:

> The only problems with the display-graphic-p solution is that it only calculates at first load. Which can cause issues when running an Emacs daemon and starting both GUI and Terminal emacsclient.

**Comment by jasonm23** [comment] 2016-09-23 14:29
> The only problems with the display-graphic-p solution is that it only calculates at first load. Which can cause issues when running an Emacs daemon and starting both GUI and Terminal emacsclient.
> 

Yes, that's correct.

**Comment by mekeor** [comment] 2016-10-07 00:02
So, is there any possible solution to this? I'd love to use the gruvbox-theme together with my Emacs daemon.

**Comment by jasonm23** [comment] 2016-10-07 00:39
The problem is making a theme with the correct color class syntax is a huge pain, and difficult to sugar away the nasty verbose syntax.

If you are having an issue because you launch the Emacs daemon under a different graphical environment, I would recommend you launch an initial instance on the display that you use most often.

If you are concerned about the error messages, you could raise a bug on the Emacs channels, but I admit that I consider it a non issue.

I would prefer a better solution but it's actually easier to make muliple versions of the theme than it is to use the color class syntax!

Perhaps that is the best solution, if you can get some +1s on this issue, I'll just roll out a 256 color terminal only version and a GUI / 24bit version.

**Comment by mekeor** [comment] 2016-11-14 15:54
What is the  “color class syntax”? Does it allow each created emacsclient frame to rethink it's graphical/display environment? Maybe I could write the color class syntax if it's too much of a pain for you but I'd need more information on it.

**Comment by jasonm23** [comment] 2016-12-02 03:56
Closing.

**Closed by jasonm23** 2016-12-02 03:56 UTC
