### ISSUE TITLE
spacemacs double themes switch

### ISSUE THREAD

**Issue by idoo** [greduan/emacs-theme-gruvbox#91] opened 2017-08-14 19:14 UTC
Currently I'm using two themes for spacemacs `light` and `dark`
```
   ;; List of themes, the first of the list is loaded when spacemacs starts.
   ;; Press <SPC> T n to cycle to the next theme in the list (works great
   ;; with 2 themes variants, one dark and one light)
   ;; First theme listed will be used as light variant, the second as the the dark
   ;; dotspacemacs-themes '(flatui
   dotspacemacs-themes '(spacemacs-light
                         spacemacs-dark)

```
and it's works well, but with current gruvbox version:
```
gruvbox-dark-soft
gruvbox-light-soft
```

I have a error message:

```
   - An error occurred while applying the theme "gruvbox-light-soft", fallback on theme "spacemacs-dark". Error was: (error
      Package ‘gruvbox-light-soft-theme-’ is unavailable)      
    - Please check the value of "dotspacemacs-themes" in your dotfile or open an issue so we can add support for the theme
      "gruvbox-light-soft". 
```
does anybody know how to fix it?

**Comment by jasonm23** [comment] 2017-08-15 00:32
Looks like it cannot find autothemer.

To work around, make sure autothemer is installed.

We will check if autothemer dependency is properly setup.

**Comment by jasonm23** [comment] 2017-08-15 00:34
> We will check if autothemer dependency is properly setup.

Seems to be ok 

How did you install the gruvbox update?

**Comment by idoo** [comment] 2017-08-15 07:45
@jasonm23 from melpa
`gruvbox-theme-20170809.719`

**Comment by jasonm23** [comment] 2017-08-15 09:24
Is autothemer installed?

It's a package dependency and it should have been automatically installed by package.el.

**Comment by jasonm23** [comment] 2017-08-15 09:25
> It's a package dependency

(Of Gruvbox)

**Comment by jasonm23** [comment] 2017-08-16 22:59
@idoo could you update with feedback please.

**Comment by martijnat** [comment] 2017-08-17 09:23
To see what was going on created a fresh spacemacs install. I don't
know much about space except that it is a popular emacs config.

- Installing gruvbox using `M-x package-install` works just fine.
- Selecting the theme using either `customize-themes` or `spacemacs/helm-themes` works fine.
- changing simply the dotspacemacs variable wasn't enough to get them to work, so I restarted spacemacs

However this led to an unexpected result, in the messages at startup I found the following:

    (spacemacs) --> deleting gruvbox-theme... [1/2]
    Package ‘gruvbox-theme-20170816.1552’ deleted.
    (Spacemacs) --> deleting autothemer... [2/2]
    Package ‘autothemer-20170112.1324’ deleted.

It seems spacemacs removes both autothemer and gruvbox when restarting
emacs. I confirmed this by reinstalling gruvbox and restarting
spacemacs, which resulted in the same removal.

I tried a different popular theme, solarized (which does not depend on
autothemer) to see if this was any different. Solarized was
automatically removed on restart as well.

Is there a special method for installing packages/themes in spacemacs
such that they don't automatically get removed on restart and did you
use this method to install gruvbox?

**Comment by jasonm23** [comment] 2017-08-17 11:43
@martijnat thanks for trying.  It's nonsense like this that had irritated me about Spacemacs since it came out.

The solution is to (perform a bunch of Spacemacs specific incantations which make little sense to anyone who is already well versed in Emacs and emacslisp.)

**Comment by ninrod** [comment] 2017-08-17 14:52
maybe this issuee should be opened in spacemacs.

**Comment by martijnat** [comment] 2017-08-18 16:24
This seems an issue with spacemacs. This happens in other themes as well and cannot be fixed by changing the theme.

**Closed** 2017-08-18 16:24 UTC
Labels: wontfix
