### ISSUE TITLE
Issue with current release

### ISSUE THREAD

**Issue by josherrickson** [greduan/emacs-theme-gruvbox#192] opened 2022-08-04 19:34 UTC
Just updated gruvbox through `list-packages`, now getting the following error when starting Emacs.

`Error (use-package): gruvbox-theme/:catch: Symbol’s value as variable is void: gruvbox-accent-00`

**Comment by jasonm23** [comment] 2022-08-05 00:38
Thanks for the report I'll check it out.

**Comment by jasonm23** [comment] 2022-08-05 00:49
I got the similar error

```
Error running timer: (void-variable gruvbox-accent-00)

```

**Comment by jasonm23** [comment] 2022-08-05 02:15
Restarting solved my issue, please restart and provide as much emacs and system info as possible if the error persists.

System: OS/ver
Emacs: Ver/compilaion options.

**Comment by josherrickson** [comment] 2022-08-05 11:55
The error persists after a reboot. Emacs 28.1 installed via homebrew on M1 Mac running 12.5. Any other diagnostic info I can provide?

**Comment by jasonm23** [comment] 2022-08-05 12:33
Is your `.emacs.d` / `init.el` / `.emacs` posted online, or can you post any code related to installation / config of theme/gruvbox?

**Comment by jasonm23** [comment] 2022-08-05 12:36
Also is the homebrew formula the regular emacs recipe or is it _exotic_, emacs-plus or emacs-mac for example.

Whatever info you have that allows me to recreate the conditions is perfect.  Emacs init should be sufficent though.

**Comment by josherrickson** [comment] 2022-08-05 14:12
My init is here: https://github.com/josherrickson/dotfiles/blob/main/init.el

It is regular homebrew formula, nothing special, `brew install emacs`.

**Comment by Remillard** [comment] 2022-08-05 17:55
I just ran into the same problem and mistakenly posted in the Vim gruvbox repo.  Here it is:

I'm running into a problem that I've got on one laptop but haven't had on any other installation. I cannot figure out what's going on. In my `init.el` file I have:

```
(use-package  gruvbox-theme
    :config
    (load-theme 'gruvbox-dark-hard t nil))

(Note, this was formerly just `t` and not `t nil` for the optional args to load-theme but I've been experimenting.) In any event, I then get the following message on loading emacs 28:

`Error (use-package) : gruvbox-theme/:catch: Symbol's value as variable is void: gruvbox-accent-00`

If I subsequently just `M-x load-theme gruvbox-dark-hard` it works just fine (or if initiated via the Menu Color Themes.

Any ideas? Seems to be an interaction with `use-package` but there's nothing `gruvbox` ought to need as a precursor is there? I might try `after-init-hook` and see but I don't have any issues on other machines where I have exactly the same call in those machine's `init.el`.

**Comment by josherrickson** [comment] 2022-08-05 19:44
Just updated to a newer version (gruvbox-theme-20220805.204) and the bug remains.

**Comment by jasonm23** [comment] 2022-08-06 01:17
@josherrickson @Remillard looks like your issues are with `use-package`.

I can't really help out much further.

**Comment by josherrickson** [comment] 2022-08-06 01:32
I'm not sure that's entirely right - I launched emacs with only the following in my init and still get the error:

```
(add-to-list 'custom-theme-load-path "~/.emacs.d/themes")
(load-theme 'gruvbox t)
```

**Comment by jasonm23** [comment] 2022-08-06 01:59
1. Move/remove any emacs config.
2. Start Emacs, `M-x package-install <return> gruvbox-theme`
3. `M-x load-theme <return> gruvbox-dark-medium`
4. ...

Considering Gruvbox is supplied through ELPA, install it that way or at least through a managed package installer, el-get, straight.el etc.

**Comment by Remillard** [comment] 2022-08-06 03:06
To my knowledge, `use-package` does load through ELPA.  It certainly isn't getting it from anywhere else like GitHub.  That said, just to test, I removed the package manually, installed the package manually, and while the `use-package` invocation still throws a caught void variable error, just doing a plain `(load-theme `gruvbox-dark-hard t)` does seem to work.  I do not have this issue on any other machine with this method, however this laptop's Emacs installation was just launched and so it downloaded things new.  I looked through gruvbox.el and can't see why it would single out `gruvbox-accent-00` because it's hardly the first variable in that gigantic list, and it and all the others are defined in the various modal `*.el` files.  So, agreed, I suspect this is more `use-package` problem than `gruvbox` (though still pretty mysterious why it singles out that variable.)

**Comment by jasonm23** [comment] 2022-08-06 03:14
The problem is you're not installing the dependency

**Comment by Remillard** [comment] 2022-08-06 03:31
What dependency exists that isn't integral to the `gruvbox-theme` package?  As far as I can tell `gruvbox-accent-00` is defined in the various theme submodules and that makes perfect sense.

As noted, `use-package` is downloading from ELPA.  It was getting everything that was in that repository.  Also this is a recent problem, the exact same invocation works on a machine I setup with Emacs at the beginning of July.  

I launched issue https://github.com/jwiegley/use-package/issues/989 on the `use-package` page.  We'll see if there's some reason it's either not referring to the submodules in `gruvbox-theme` or if there's some other reason it's picking out `gruvbox-accent-00` out of all the hundreds of others.

**Comment by jasonm23** [comment] 2022-08-06 05:44
As noted, if the package is installed through package.el and there is no involvement with use-package, the theme is working fine.

If you try that, you'll see.

This aside, I can't help you with other configurations you'll need to work that out by yourself. 

Please don't assume that I think there is something inherently wrong with `use-package`, I don't.  I am just making it clear that we're not a general purpose `emacs.d/init.el` free support service.

As posted already, the gruvbox theme collection is clearly working, and you can reproduce this by following the steps above.

**Comment by jasonm23** [comment] 2022-08-06 05:49
If you would like to make a note of the dependency tree required, remove `.emacs.d` / `init.el` and restart emacs, and do package-install grubox-theme.  The dependencies will be installed along with gruvbox and you make inspect them.

**Comment by jasonm23** [comment] 2022-08-06 05:52
Current dependency tree for gruvbox.

```
autothemer-0.2.3
dash-2.19.1
gruvbox-theme-1.27.0
```

**Comment by josherrickson** [comment] 2022-08-06 10:21
> 1. Move/remove any emacs config.
> 2. Start Emacs, `M-x package-install <return> gruvbox-theme`
> 3. `M-x load-theme <return> gruvbox-dark-medium`
> 4. No errors.
> 
> Considering Gruvbox is supplied through ELPA, install it that way or at least through a managed package installer, el-get, straight.el etc.

Here's what I did.

1) Rename `.emacs_d/` to something else
2) Start emacs.
3) Eval `(add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/"))`
4) Run `M-x package-install <return> gruvbox-theme`
5) Run `M-x load-theme <return> gruxbox` as stated on the README, https://github.com/greduan/emacs-theme-gruvbox#no-packageel

This gives me the error we've been discussing.

If I run step 5 as `M-x load-theme <return> gruxbox-dark-soft` it runs without error. Doesn't this imply that while you're correct, there is a way to load it without error, the fact that `M-x load-theme <return> gruxbox` produces an error is entirely on gruvbox's side, not use-package?

**Comment by jasonm23** [comment] 2022-08-06 10:58
Gruvbox is on ELPA.

By clearing . emacs.d and any other init.el / .emacs.d and just doing 

    M-x package-install RET  gruvbox-theme RET

You get a working install.  There's nothing else to do.

If you get errors beyond that it's outside the scope of the theme.

**Comment by jasonm23** [comment] 2022-08-08 03:46
The is fixed in  the latest  update.  Apologies, the error was due to using `gruvbox` as theme name,  which didn't have the new accent colors.

**Closed by jasonm23** 2022-08-08 03:46 UTC
